apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-nodejs
  name: all-language-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-nodejs
    spec:
      containers:
      - image: kennethfoo24/all-language-nodejs:ccb6e53597664136b0d0bed232ac8a989c8127c4
        name: all-language-nodejs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PYTHON_SERVICE_URL
          value: "http://all-language-python-lb:5000/python"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-nodejs
  name: all-language-nodejs-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: all-language-nodejs
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-python
  name: all-language-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-python
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-python
    spec:
      containers:
      - image: kennethfoo24/all-language-python:05387b4d12805f33850b9684364e73de292b2c9c
        name: all-language-python
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-python
  name: all-language-python-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: all-language-python
  type: ClusterIP
