apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-nodejs
  name: all-language-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-nodejs
    spec:
      containers:
      - image: kennethfoo24/all-language-nodejs:latest
        name: all-language-nodejs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PYTHON_SERVICE_URL
          value: "http://all-language-python-lb:5000/python"
        - name: DD_LOGS_INJECTION
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-nodejs
  name: all-language-nodejs-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: all-language-nodejs
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-python
  name: all-language-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-python
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-python
    spec:
      containers:
      - image: kennethfoo24/all-language-python:latest
        name: all-language-python
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: JAVA_SERVICE_URL
          value: "http://all-language-java-lb:8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-python
  name: all-language-python-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: all-language-python
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-java
  name: all-language-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-java
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-java
    spec:
      containers:
      - image: kennethfoo24/all-language-java:latest
        name: all-language-java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GOLANG_SERVICE_URL
          value: "http://all-language-golang-lb:8000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-java
  name: all-language-java-lb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: all-language-java
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-golang
  name: all-language-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-golang
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-golang
    spec:
      containers:
      - image: kennethfoo24/all-language-golang:latest
        name: all-language-golang
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DOTNET_SERVICE_URL
          value: "http://all-language-dotnet-lb:5555"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-golang
  name: all-language-golang-lb
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: all-language-golang
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-ruby
  name: all-language-ruby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-ruby
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-ruby
    spec:
      containers:
      - image: kennethfoo24/all-language-ruby:f8c5feb5581866c06edd03102e63fe3c6abc5bdf
        name: all-language-ruby
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-ruby
  name: all-language-ruby-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: all-language-ruby
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-dotnet
  name: all-language-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-dotnet
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-dotnet
    spec:
      containers:
      - image: kennethfoo24/all-language-dotnet:latest
        name: all-language-dotnet
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
        env:
        - name: RUBY_SERVICE_URL
          value: "http://all-language-ruby-lb/ruby"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-dotnet
  name: all-language-dotnet-lb
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: all-language-dotnet
  type: ClusterIP

