apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: all-language-golang
  name: all-language-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-language-golang
  strategy: {}
  template:
    metadata:
      labels:
        app: all-language-golang
    spec:
      containers:
      - image: kennethfoo24/all-language-golang:latest
        name: all-language-golang
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: all-language-golang
  name: all-language-golang-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: all-language-golang
  type: LoadBalancer
status:
  loadBalancer: {}