name: Docker Image CI PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: kennethfoo24   # Docker Hub username/namespace
      IMAGE_NAME: all-language-php      # Image name in Docker Hub
    steps:
      - uses: actions/checkout@v4

      # Not strictly required for PHP builds (no Node install needed)

      - name: Build & Push Docker Image (PHP)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
          registry: docker.io
          directory: php
          dockerfile: php/Dockerfile     # Dockerfile path
          tags: ${{ github.sha }}, latest
          # Use Actions context so the values resolve correctly
          buildArgs: 'DD_GIT_REPOSITORY_URL=github.com/kennethfoo24/all-language-php,DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)'  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
